FROM debian:bullseye

ENV NAME=debian-toolbox VERSION=bullseye
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Debian toolbox containers" \
      maintainer="Michael J. Manley <mjmanley@ntge.net>"

RUN apt-get update && \
    apt-get -y install sudo libcap2-bin && \
    apt-get clean

COPY extra-packages /
RUN apt-get -y install $(cat extra-packages)
RUN rm /extra-packages

RUN sed -i -e 's/ ALL$/ NOPASSWD:ALL/' /etc/sudoers

RUN touch /etc/localtime
RUN echo VARIANT_ID=container >> /etc/os-release

CMD /bin/bash

